---
apiVersion: lmtd.lifememory.team/v1beta1
kind: Challenge
labels:
  # [この設定固有の識別子の設定]
  # 通常は challenge-(問題名) が指定されます。
  importer.lmtd.lifememory.team/unique-key: challenge-simplemod
spec:
  # [問題名の設定]
  name: simplemod

  # タグ
  tag:
    - author:shift-crops

  # [表示順の設定]
  # ※ この値については何もしなくて大丈夫です
  order: 3

  # [公開設定]
  # ※ この値については何もしなくて大丈夫です
  isPublic: true

  # [ジャンルの設定]
  ownerCategoryUniqueKey: category-pwnable

  # [配布ファイルの設定]
  dists:
  - name: "simplemod"
    uploadType: dirCompress
    replaceKey: "<FILES>"

  # [問題文の設定]
  description: |
    Which bytes do you want to modify?

    ```
    nc simplemod.seccon.games 7250
    ```

    <FILES>

    *NOTICE*  
    This challenge is running with home-built glibc-2.3x.  
    Excessive bruteforce is not required.  
    Attacks that overload the server are prohibited.

  server:
    ports:
      - 7250
    protocol: tcp
    docker: true
    plan: small
    tags: ["filter:plz"]
